### ISSUE TITLE
v133 开始最大化 最小化和关闭按钮偏左

### ISSUE THREAD

**Issue by Leavesr** [MapoMagpie/firefox-compact-ui#1]
<img width="1920" alt="2024-11-04_134921" src="https://github.com/user-attachments/assets/241f80c5-50d4-49d9-86e0-7a0eecd5bb2a">
如图所示，

**Comment by MapoMagpie** [comment]
已更新。你用的是开发者版本吗，最新的正式版似乎只到132。

另外，这个调整是关于菜单栏的。

**Comment by Leavesr** [comment]
> 已更新。你用的是开发者版本吗，最新的正式版似乎只到132。
> 
> 另外，这个调整是关于菜单栏的。

多谢了
用的每夜版，firefox从v133开始应该动了ui，部分样式都有问题

**Comment by MapoMagpie** [comment]
还有什么样式有问题？

**Comment by Leavesr** [comment]
> 还有什么样式有问题？

浮动隐藏书签，应该在标签栏下方，但是现在和标签栏重叠，如图2：
<img width="1242" alt="2024-11-04_194955" src="https://github.com/user-attachments/assets/01f35920-e9d4-4b58-8344-7ea0be5af956">

<img width="938" alt="2024-11-04_194511" src="https://github.com/user-attachments/assets/1f830992-fe79-4003-850b-a62b520efda1">

用的代码：
```

/*书签栏自动隐藏样式<一>*/
#PersonalToolbar {
          display: block;
          z-index: 1;
  transform: perspective(1000px) rotateX(-90deg);
  transform-origin: top !important;
  visibility: hidden !important;
  margin-top: 25px !important;
  padding:6px 2px !important;
  height:auto !important;
  width: 100% !important;
  position: fixed !important;
  opacity: 0;
/*  -moz-transition:  .3s ease-out !important;*/
  transition:  .3s ease-out !important;
/*  -moz-transition-delay: 0.8s!important;      /*设置多少秒bookmark消失*/
  transition-delay: 0.3s!important;
}
#nav-bar:hover ~ #PersonalToolbar,#PersonalToolbar:hover /*地址栏+标签栏为#navigator-toolbox:hover > */
{
  transform: rotateX(0deg);
  visibility: visible !important;
  opacity: 1;                               /*动画基于此参数*/
  transition: .3s ease-in !important;
  transition-delay: 0.3s!important;     /*设置多少秒后延迟出现*/
}


/*书签栏自动隐藏样式<二>*/
/*
#PersonalToolbar {
   width: 100% !important;
   position: fixed !important;
   margin-top: 25px !important;
   transition: .1s ease-out 1s!important;
   z-index: -1 !important;
   opacity: 0 !important;

   padding:5px 2px !important;
   height:auto !important;
   position: fixed !important;
}
#nav-bar:hover~#PersonalToolbar,#PersonalToolbar:hover{
   margin-top: 27px !important;
   transition: .1s ease-in 1s!important;
   z-index: 1  !important;
   opacity: 1 !important;
}
*/

/*书签按钮下拉菜单宽度*/
/*#BMB_bookmarksPopup{
  min-width:220px !important;
    max-width:220px !important;
}*/   

/*书签项二级菜单宽度*/
.bookmark-item menuitem {
    min-width:300px !important;
    max-width:300px !important;
    padding:6px !important;
}     

/* 添加和编辑书签时自动弹出面板
#editBookmarkPanel [collapsed="true"],#editBMPanel_descriptionRow,#editBMPanel_locationRow {
    visibility:visible !important
}
#editBookmarkPanel *|*.textbox-input:-moz-placeholder {
    color:transparent !important;
    text-shadow:none !important;
}
#editBMPanel_folderTree {
    min-height:15em !important;
}
#editBMPanel_tagsSelector {
    max-height:4em !important;
}
#editBMPanel_descriptionField {
    max-height:3em !important;
}
*/

/*书签工具栏文件夹图标*/
#PersonalToolbar toolbarbutton[class="bookmark-item"][type="menu"],menu[container="true"][class="menu-iconic bookmark-item"] {
    list-style-image: url("../image/bookmark-toolbar-folder.svg") !important;
}   
/*书签文件夹图标及网站图标自动补全*/
menu.bookmark-item:not([query]):not([label="Bookmarks Toolbar"]) {
    list-style-image: url("../image/bookmark-folder.svg") !important;
}

/*自动隐藏文字标签
    toolbarbutton.bookmark-item[type="menu"] label,
    toolbarbutton.bookmark-item:not([type="menu"]) label
    { display: none !important; }
    toolbarbutton.bookmark-item[type="menu"]:hover label,
    toolbarbutton.bookmark-item:not([type="menu"]):hover label
    { display: block !important; }
*/
```

**Comment by MapoMagpie** [comment]
浮动书签核心部分
```css
/* 导航栏(浏览器最上层的工具栏，内部包含了所有的bar，如标签栏、地址栏、书签栏等)
   此项设置为unset后，即可显示其内部元素使用了fixed定位且超出导航栏位置的元素。
*/
#navigator-toolbox {
  z-index: unset !important;
}
/* 浮动书签的父元素，需要增加其z-index值 */
#PlacesToolbar {
  z-index: 10 !important;
}
/* 浮动书签 */
#PlacesToolbarItems {
  position: fixed !important;
  top: var(--globle-height);
  left: 0;
  width: 100vw !important;
  visibility: hidden !important;
}
/* 鼠标移动到导航栏(浏览器最上层的工具栏，内部包含了所有的bar，如标签栏、地址栏、书签栏等)时显示浮动书签 */
#navigator-toolbox:hover #PlacesToolbarItems, 
/* 鼠标移动至浮动书签自身时，保持显示 */
#PlacesToolbarItems:hover {
  visibility: visible !important;
}
```

由于我不使用浮动标签，所以剩下的动画效果、细节之类的你自己改吧。
我平常都是点击左上角的图标
![grim_20241106_130825](https://github.com/user-attachments/assets/3b1c77c8-44ec-4587-9508-0cf98f000c42)
